name: scat
channels:
  - cond-forge
  - michael--s--phillips
  - defaults
dependencies:
  - python  # You can adjust the Python version if needed
  - tk
  - matplotlib
  - spectral
  - numpy
  - rasterio
  - opencv
  - hypyrameter
